### ISSUE TITLE
Forever 'Loading jobs...'

### ISSUE THREAD

**Issue by mscheper** [backuity/cinnamon-jenkins-applet#11]
I've just updated to Mint 18.2 and I've added v1.3.0 of cinnamon-jenkins-applet to a panel. I haven't managed to get it to do anything useful, though, connecting to Jenkins 2.46.2.

I've set Jenkins URL to exactly the same URL that I use to look at Jenkins in a browser, with the same Username and Password that I use to log in. (I find it disturbing that the password is visible in the configuration dialogue, but I suppose it doesn't matter that much.)

I initially left 'Project Filtering' blank, because there only was one project, but now I've added its name (exactly as under 'Name' in the table at the URL), but that didn't make a difference. I've tried turning off _Validate SSL Certificate_ as well. Everything else is off/default.

Am I doing anything wrong? Can I diagnose this anywhere? There doesn't seem to be any kind of log in `$HOME/.local/share/cinnamon/applets/jenkins@backuity.org`

Thanks!

**Comment by backuitist** [comment]
Hey, sorry but this project is now maintained there: https://github.com/linuxmint/cinnamon-spices-applets/tree/master/jenkins%40backuity.org
I'll update the README
