### ISSUE TITLE
Support authentication with API token

### ISSUE THREAD

**Issue by akikoskinen** [backuity/cinnamon-jenkins-applet#5]
Although I have entered a valid username/password pair into the configuration the applet doesn't authenticate to the server. I think it doesn't even try. Checking from `~/.cinnamon/glass.log` there is no line containing "Authenticating with &lt;username&gt;" as could be expected by reading the code.

More info: when a request is made to the Jenkins server unauthenticated the server responds with a 403 status code and redirects to a login page (to `/login?from=%2Fapi%2Fjson` to be exact).

The [`SoupSession`](https://developer.gnome.org/libsoup/unstable/SoupSession.html#SoupSession.description) authentication method that the applet uses seems to by default only support Basic and Digest authentication methods and the 403 status code received from the server is probably neither.

I couldn't find any setting from Jenkins that would change its behaviour related to this.

**Comment by backuitist** [comment]
That's correct. I'm using a reverse proxy that uses basic auth with https. I'll rephrase the issue.

Of course, you're welcome to add support for that, I think it should be fairly straighforward:

https://wiki.jenkins-ci.org/display/JENKINS/Authenticating+scripted+clients

**Comment by backuitist** [comment]
Ok, i've checked and it works!
